name: Build RocketMQ Console on CentOS ARM64

on:
  push:
    branches:
      - master  # 触发工作流的分支
  pull_request:
    branches:
      - master  # 触发工作流的分支
jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions 的主机环境
    container:
      image: arm64v8/centos:7  # 使用 CentOS 7 ARM64 的 Docker 镜像
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Install dependencies
        run: |
          yum install -y java-1.8.0-openjdk-devel maven  # 安装 JDK 8 和 Maven
          java -version
          mvn -version

      - name: Build with Maven
        run: mvn clean package -DskipTests  # 使用 Maven 编译打包

      - name: Upload Artifact
        uses: actions/upload-artifact@v2  # 上传构建结果
        with:
          name: rocketmq-console
          path: target/*.jar  # 上传 target 目录下的 JAR 文件
