name: Build RocketMQ Console

on:
  push:
    branches:
      - main  # 触发工作流的分支
  pull_request:
    branches:
      - main  # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ARM64 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Set up JDK 8
        uses: actions/setup-java@v2  # 设置 JDK 8 环境
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests  # 使用 Maven 编译打包

      - name: Upload Artifact
        uses: actions/upload-artifact@v2  # 上传构建结果
        with:
          name: rocketmq-console
          path: target/*.jar  # 上传 target 目录下的 JAR 文件
