name: Build RocketMQ Console on ARM64

on:
  push:
    branches:
      - master  # 触发工作流的分支
  pull_request:
    branches:
      - master  # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest-arm64  # 使用 GitHub 提供的 ARM64 运行器
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-8-jdk maven  # 安装 JDK 8 和 Maven
          java -version
          mvn -version

      - name: Build with Maven
        run: mvn clean package -DskipTests  # 使用 Maven 编译打包

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # 使用 v4 版本上传构建结果
        with:
          name: rocketmq-console
          path: target/*.jar  # 上传 target 目录下的 JAR 文件
